# Titanic Survival Prediction with Logistic Regression

This project predicts whether a passenger survived the Titanic disaster using machine learning.

## 1. Import Libraries

We import NumPy and Pandas for data handling, Seaborn for the Titanic dataset, Matplotlib for visualization, and warning controls.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

## 2. Load the Dataset

The Titanic dataset is loaded from Seaborn. Each row represents one passenger.

In [3]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


## 3. Explore the Dataset

We inspect the column names, data types, and missing values before preparing the data.

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    str     
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    str     
 8   class        891 non-null    category
 9   who          891 non-null    str     
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str     
 13  alive        891 non-null    str     
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 100.4 KB


In [6]:
df.drop(['deck', 'embark_town','alive','class', 'who', 'adult_male'], axis = 1, inplace = True)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    str    
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    str    
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), str(2)
memory usage: 61.8 KB


## 4. Data Preprocessing

Unnecessary columns are removed. Missing ages are replaced with the average age, and rows with missing embarkation values are removed.

In [8]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
alone         0
dtype: int64

In [9]:
df["age"] = df["age"].fillna(df["age"].median(), inplace = True)

it select the age colomn and replace all its null values with the mean of age column

In [10]:
df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    2
alone       0
dtype: int64

In [11]:
# --- Remove duplicate rows ---
df.columns = df.columns.str.strip()
df_clean = df.drop_duplicates().reset_index(drop=True)

# Check columns
print(df_clean.columns.tolist())

# --- If you want to reset the index after dropping ---
df = df_clean.reset_index(drop=True)

['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'alone']


In [12]:
df.dropna(subset=["embarked"], inplace=True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 773 entries, 0 to 774
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  773 non-null    int64  
 1   pclass    773 non-null    int64  
 2   sex       773 non-null    str    
 3   age       773 non-null    float64
 4   sibsp     773 non-null    int64  
 5   parch     773 non-null    int64  
 6   fare      773 non-null    float64
 7   embarked  773 non-null    str    
 8   alone     773 non-null    bool   
dtypes: bool(1), float64(2), int64(4), str(2)
memory usage: 59.6 KB


## 5. Convert Text into Numbers

Machine-learning models require numerical input. Therefore, the `sex` and `embarked` columns are converted into numerical labels.

In [14]:
import sklearn.preprocessing
le = sklearn.preprocessing.LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked']) # S=2, C=0, Q=1

In [15]:
# Truncate/round first, then cast to nullable integer
df = df.round().astype('Int64')

In [16]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,1,22,1,0,7,2,0
1,1,1,0,38,1,0,71,0,0
2,1,3,0,26,0,0,8,2,1
3,1,1,0,35,1,0,53,2,0
4,0,3,1,35,0,0,8,2,1
...,...,...,...,...,...,...,...,...,...
770,0,3,0,39,0,5,29,1,0
771,1,1,0,19,0,0,30,2,1
772,0,3,0,28,1,2,23,2,0
773,1,1,1,26,0,0,30,0,1


## 6. Separate Features and Target

`X` contains the passenger information used for prediction.  
`y` contains the target value:

- `0` = Did not survive
- `1` = Survived

In [17]:
x = df.drop('survived', axis = 1)
y = df['survived']

## 7. Split the Dataset

The data is divided into training and testing sets. The model learns from the training data and is evaluated on unseen test data.

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

## 8. Train the Logistic Regression Model

Logistic Regression is a classification algorithm used to predict one of two outcomes: survived or did not survive.

In [19]:
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

# 1. Fill NaNs using median of each feature
imputer = SimpleImputer(strategy='median')
x_train_imputed = imputer.fit_transform(x_train)
x_test_imputed = imputer.transform(x_test)

# 2. Fit model
model = LogisticRegression(max_iter=1000)
model.fit(x_train_imputed, y_train)

,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is '

## 9. Make Predictions

The trained model predicts survival outcomes for passengers in the test dataset.

In [20]:
y_pred = model.predict(x_test)

In [21]:
y_pred

array([1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1.,
       0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0.,
       0., 0.])

In [22]:
y_test

364    1
680    1
516    0
169    0
731    1
      ..
55     0
755    1
361    0
539    0
376    1
Name: survived, Length: 155, dtype: Int64

## 10. Evaluate the Model

Accuracy shows the percentage of correct predictions. The confusion matrix and classification report provide additional performance details.

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report         

In [24]:
accuracy_score(y_test, y_pred)

0.8258064516129032

In [25]:
confusion_matrix(y_test, y_pred)

array([[69,  9],
       [18, 59]])

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.79      0.88      0.84        78
         1.0       0.87      0.77      0.81        77

    accuracy                           0.83       155
   macro avg       0.83      0.83      0.83       155
weighted avg       0.83      0.83      0.83       155



--------------

### Model based on Naive Bayes Classifier 

In [27]:
from sklearn.naive_bayes import GaussianNB
model_NB = GaussianNB()
model_NB.fit(x_train, y_train)


,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)number of training samples observed in each class.","ndarray[float64](2,)","[377.,241.]"
"class_prior_ class_prior_: ndarray of shape (n_classes,)probability of each class.","ndarray[float64](2,)","[0.61,0.39]"
"classes_ classes_: ndarray of shape (n_classes,)class labels known to the classifier.","ndarray[float64](2,)","[0.,1.]"
epsilon_ epsilon_: floatabsolute additive value to variances.,float64,2.953e-06
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](8,)","['pclass','sex','age',...,'fare','embarked','alone']"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,8
"theta_ theta_: ndarray of shape (n_classes, n_features)mean of each feature per class.","ndarray[float64](2, 8)","[[ 2.5 , 0.82,30.12,...,23.44, 1.64, 0.63], [ 1.91, 0.36,28.26,...,52.44, 1.36, 0.44]]"
"var_ var_: ndarray of shape (n_classes, n_features)Variance of each feature per class... versionadded:: 1.0","ndarray[float64](2, 8)","[[ 0.57, 0.15, 178.56,...,1029.7 , 0.52, 0.23], [ 0.73, 0.23, 210.38,...,5448.74, 0.81, 0.25]]"


In [28]:
y_pred_NB = model_NB.predict(x_test)

In [29]:
y_pred_NB

array([0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0.,
       1., 0.])

In [30]:
y_test

364    1
680    1
516    0
169    0
731    1
      ..
55     0
755    1
361    0
539    0
376    1
Name: survived, Length: 155, dtype: Int64

### evalute the Model

In [31]:
model_NB.score(x_test, y_test)

0.7612903225806451

In [32]:
accuracy_score(y_test, y_pred_NB)

0.7612903225806451

In [33]:
confusion_matrix(y_test, y_pred_NB)

array([[70,  8],
       [29, 48]])

In [34]:
print(classification_report(y_test, y_pred_NB ))

              precision    recall  f1-score   support

         0.0       0.71      0.90      0.79        78
         1.0       0.86      0.62      0.72        77

    accuracy                           0.76       155
   macro avg       0.78      0.76      0.76       155
weighted avg       0.78      0.76      0.76       155



---

## Model based on Decision Tree Classifier

In [35]:
from sklearn.preprocessing import StandardScaler    
scaler = StandardScaler()
        
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)   

In [36]:
# from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
model_DT = DecisionTreeClassifier(random_state=42)
# scores = cross_val_score(model_DT, x, y, cv = 10)
# print(scores)
# print(scores.mean())                        
model_DT.fit(x_train_scaled, y_train)   

,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary <random_state>` for details.",42
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'gini'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples 

In [37]:
y_pred_DT = model_DT.predict(x_test_scaled)

In [38]:
accuracy_score(y_test, y_pred_DT)

0.7290322580645161

In [39]:
confusion_matrix(y_test, y_pred_DT)

array([[54, 24],
       [18, 59]])

In [40]:
print(classification_report(y_test, y_pred_DT))

              precision    recall  f1-score   support

         0.0       0.75      0.69      0.72        78
         1.0       0.71      0.77      0.74        77

    accuracy                           0.73       155
   macro avg       0.73      0.73      0.73       155
weighted avg       0.73      0.73      0.73       155



----

## SVM Model

### import svm model

In [41]:
from sklearn.svm import SVC
model_SVC = SVC()
model_SVC.fit(x_train_scaled, y_train)

,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide <shrinking_svm>`.",True
,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide <scores_probabilities>`...deprecated:: 1.9 The `probability` parameter is deprecated and will be removed in 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`.",'deprecated'
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


In [42]:
y_pred_SVC = model_SVC.predict(x_test_scaled)

In [43]:
accuracy_score(y_test, y_pred_SVC)

0.8258064516129032

In [44]:
confusion_matrix(y_test, y_pred_SVC)

array([[76,  2],
       [25, 52]])

In [45]:
print(classification_report(y_test, y_pred_SVC))

              precision    recall  f1-score   support

         0.0       0.75      0.97      0.85        78
         1.0       0.96      0.68      0.79        77

    accuracy                           0.83       155
   macro avg       0.86      0.82      0.82       155
weighted avg       0.86      0.83      0.82       155



---

## cross validation

In [46]:
x


,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,3,1,22,1,0,7,2,0
1,1,0,38,1,0,71,0,0
2,3,0,26,0,0,8,2,1
3,1,0,35,1,0,53,2,0
4,3,1,35,0,0,8,2,1
...,...,...,...,...,...,...,...,...
770,3,0,39,0,5,29,1,0
771,1,0,19,0,0,30,2,1
772,3,0,28,1,2,23,2,0
773,1,1,26,0,0,30,0,1


In [47]:
from sklearn.model_selection import cross_val_score

In [48]:
scaler = StandardScaler()   # scaler object used to standardize the data 
# for example: x = scaler.fit_transform(x) transforms the data like x = (x - mean(x)) / std(x)  
x_scaled = scaler.fit_transform(x)

In [49]:
x_scaled

array([[ 0.88090573,  0.77486391, -0.54825479, ..., -0.52995073,
         0.59027897, -1.1344524 ],
       [-1.46716368, -1.2905492 ,  0.61783553, ...,  0.6915804 ,
        -1.8895343 , -1.1344524 ],
       [ 0.88090573, -1.2905492 , -0.25673221, ..., -0.51086431,
         0.59027897,  0.88148255],
       ...,
       [ 0.88090573, -1.2905492 , -0.11097092, ..., -0.22456795,
         0.59027897, -1.1344524 ],
       [-1.46716368,  0.77486391, -0.25673221, ..., -0.09096298,
        -1.8895343 ,  0.88148255],
       [ 0.88090573,  0.77486391,  0.18055166, ..., -0.51086431,
        -0.64962767,  0.88148255]], shape=(773, 8))

In [50]:
scores = cross_val_score(model_SVC, x_scaled, y, cv = 10, scoring='accuracy')

In [51]:
print(scores)
print(scores.mean())

[0.78205128 0.80769231 0.75641026 0.84415584 0.79220779 0.79220779
 0.80519481 0.75324675 0.90909091 0.84415584]
0.8086413586413587


In [52]:
print(scores.std())

0.04435003462029847
